### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by geshumin** [andimarafioti/audioContextEncoder#16]
excuse me. i found so many files in you project, but the readme.md is not clear, you said: "To train the network, execute in the parent folder python paperArchitecture.py", i even can not find it . please tell me more information about your training process. Thank you so much.

**Comment by andimarafioti** [comment]
Hey, I just found this. I think you were right, somewhere along the line I deleted 'paperArchitecture.py' and made two files 'trainComplexArchitecture.py' and 'trainMagnitudeArchitecture.py' but never adapted the readme. My bad, I'm sorry.
