### ISSUE TITLE
No module named 'architecture'

### ISSUE THREAD

**Issue by mirbagheri** [andimarafioti/audioContextEncoder#19]
I get the following error when trying to unpickle ''magnitude_network_parameter.pkl"
Traceback (most recent call last):
  File "/home/akclee/miniconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-b21cb24e5ed3>", line 2, in <module>
    data = pickle.load(f)
  File "/home/akclee/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'architecture'

**Comment by andimarafioti** [comment]
Hey Mirbagheri, the pickled file creates some classes from this repo, so it expects to be unpickled at the root folder. If you try to unpickle the file at another folder you would get this error. I just downloaded a clean version of the repo and unpickling the file at the root folder works perfectly but trying to unpickle it at another folder fails with that error. Could you check that it works for you on the root folder? Thanks!

**Comment by mirbagheri** [comment]
Thanks! Your hint solved the problem.
